IHRACP-5801: Pubdate Investigation
iheartradio/pyPodcastParser pull request #14
Opened 2023-07-06 14:55 UTC by poonamshinde-ihm

## JIRA Ticket
- [Title](https://ihm-it.atlassian.net/browse/IHRACP-5801)

## Description
#### Major Changes:
- Added PDT Timezone in pytz timezon for PDT to EST conversion
- unit test added for PDT to EST conversion

## Related PRs

-

2023-07-06 15:32 UTC, IanNoyes approved these changes
Tested this in whisper with a PDT timezone and EST timezone.  The PDT timezone episodes were converted to EST as expected and the EST timezones imported as normal.  Good work!

2023-07-06 15:33 UTC, IanNoyes requested changes

2023-07-06 15:33 UTC, IanNoyes commented on setup.py
> +    version='1.9.0.dev',
I lied, let's change this version number to not include the dev tag.  After that we're good.

2023-07-10 09:32 UTC, poonamshinde-ihm commented on setup.py
> +    version='1.9.0.dev',
sure Thanks

2023-07-10 10:51 UTC, poonamshinde-ihm commented on setup.py
> +    version='1.9.0.dev',
done

2023-07-10 16:47 UTC, IanNoyes approved these changes

2023-07-11 15:18 UTC, daleyp24 commented on pypodcastparser/Item.py
> +'PDT' : 'America/Los_Angeles'
have we investigated in kibana any other failing timezones or asked nate

2023-07-11 15:46 UTC, daleyp24 commented
need to address linter errors in tox

2023-07-11 15:47 UTC, daleyp24 requested changes
see comments

2023-07-11 17:09 UTC, poonamshinde-ihm commented
> need to address linter errors in tox

fixed

2023-07-12 15:15 UTC, daleyp24 approved these changes

2023-07-13 10:13 UTC, merged